name: Test

on:
  push:
    branches:
      - "**"
      - "!main"
  pull_request:
    branches:
      - "**"
      - "!main"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install required system deps
        run: sudo apt install g++ pkg-config libx11-dev libasound2-dev libudev-dev

      - uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: Run unit/functional tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          toolchain: nightly
        env:
          PKGLS_LOG: debug
          RUST_BACKTRACE: 1
